## JavaScript Linter rules ##

# Env Vars #
env:
  browser: true
  es2021: true

extends: 'eslint:recommended'

# Parser vars #
parserOptions:
  ecmaVersion: 2021

# Rules #
rules: {
  "semi": [2, "always"],
  "indent": [1, 2]
}
