name: Lint Code Base

on:
  pull_request:
    branches: [main]

jobs:
  check-code-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@latest
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@latest
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
