name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      # Lint code
      - name: Lint Code Base
        uses: github/super-linter/slim@latest
        env:
          # Validate only new files
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          OUTPUT_DETAILS: detailed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          VALIDATE_JAVASCRIPT_ES: true
          GROOVY_CONFIG_FILE: .groovylintrc.json
          VALIDATE_GROOVY: true
